##swagger 配置
swagger:
  enabled: true
  title: TEST Api
  authorization:
    key-name: authorization
  docket:
    test:
      base-package: com.snow.xiaoyi.module.test
    user:
      base-package: com.snow.xiaoyi.module.user
    file:
      base-package: com.snow.xiaoyi.module.file
    security:
      base-package: com.snow.xiaoyi.module.security